Collect inspection build logs as well
Signed-off-by: Marek Cermak <macermak@redhat.com>

modified:   amun/api_v1.py
modified:   openshift/amunInspectionWorkflow-template.yaml
modified:   openshift/amunInspectionWorkflowWithCPU-template.yaml
modified:   workflows/templates/inspection-build-template.yaml
modified:   workflows/templates/inspection-build-with-cpu-template.yaml
modified:   workflows/templates/inspection-results-template.yaml

diff --git a/workflows/templates/inspection-results-template.yaml b/workflows/templates/inspection-results-template.yaml
--- a/workflows/templates/inspection-results-template.yaml
+++ b/workflows/templates/inspection-results-template.yaml
@@ -20,11 +20,14 @@ spec:
       - name: kind
         value: pods
       - name: selector
-        value: ''
+        value: ""
       - name: registry
         value: docker-registry.default.svc:5000
       - name: thoth-infra-namespace
         value: "{{workflow.namespace}}"
+      # Exit
+      - name: exit
+        value: "false"
     outputs:
       artifacts:
       - name: output
@@ -50,6 +53,11 @@ spec:
 
         # Output logs for easier debugging
         cat $results/*.json | jq -s
+
+        if [ "true" == "{{inputs.parameters.exit}}" ]; then
+          >&2 echo "Workflow failure in the previous steps. Exitting."
+          exit 1
+        fi
 
       resources:
         limits:
